<?php
	class m_custom extends CI_Model{		
		
		function getADt_FR_MMA($uuidMMA)
			{
				$query = 
					'SELECT MMA.UUID_MMA, MMA.UUID_USER, MMA.UUID_APL_01, MMA.UUID_APL_02, MMA.NO_DOKUMEN AS NO_DOKUMEN00, 
					APL01.NO_DOKUMEN AS NO_DOKUMEN01, APL02.NO_DOKUMEN AS NO_DOKUMEN02, SKE.NOMOR_SKEMA, SKE.NAMA_SKEMA, 
					USER.USER_NAME, MMA.DTM_CRT, APL01.TUJUAN_ASESMEN
					FROM FR_MMA AS MMA
					LEFT JOIN FR_APL_01 AS APL01 ON MMA.UUID_APL_01 = APL01.UUID_APL01
					LEFT JOIN FR_APL_02 AS APL02 ON MMA.UUID_APL_02 = APL02.UUID_APL02
					LEFT JOIN SKEMA AS SKE ON APL01.UUID_SKEMA = SKE.UUID_SKEMA
					LEFT JOIN USER ON MMA.UUID_USER = USER.UUID_USER
					WHERE mma.uuid_mma = \''.$uuidMMA.'\'';
				return $this->db->query($query);
			}
			
		function getDt_listAnswer($uuidApl01, $uuidApl02)
			{
				$query = 
					'SELECT 
						UK.UUID_UK, EK.UUID_EK, KUK.UUID_KUK, UK.JUDUL_UK, KUK.PERTANYAAN, KUK.PERNYATAAN, 
						ANS_APL_02.IS_KOMPETEN, ANS_APL_02.UUID_BUKTI
					FROM ANSWER_APL_02 AS ANS_APL_02
					LEFT JOIN FR_APL_02 AS APL02 ON ANS_APL_02.UUID_APL02 = APL02.UUID_APL02
					LEFT JOIN UNIT_KOMPETENSI UK ON ANS_APL_02.UUID_UK = UK.UUID_UK
					LEFT JOIN ELEMEN_KOMPETENSI EK ON ANS_APL_02.UUID_EK = EK.UUID_EK
					LEFT JOIN KRITERIA_UNJUK_KERJA KUK ON ANS_APL_02.UUID_KUK = KUK.UUID_KUK
					WHERE ANS_APL_02.UUID_APL02 = \''.$uuidApl02.'\' AND ANS_APL_02.UUID_UK IN (SELECT UUID_UK FROM APL01_UK WHERE UUID_APL01 = \''.$uuidApl01.'\')
					ORDER BY UK.KODE_UK, EK.NOMOR_EK, KUK.NOMOR_KUK';
				return $this->db->query($query);
			}
			
		function getDt_listBukti($uuidApl01)
			{
				$query = 
					'SELECT 01_BUK.UUID_APL01, 01_BUK.UUID_BUKTI, BUK.KETERANGAN
					FROM APL01_BUKTI AS 01_BUK 
					LEFT JOIN BUKTI AS BUK ON 01_BUK.UUID_BUKTI = BUK.UUID_BUKTI
					WHERE 01_BUK.UUID_APL01 = \''.$uuidApl01.'\'
					ORDER BY BUK.KETERANGAN';
				return $this->db->query($query);
			}
	}
?>